### ISSUE TITLE
Where can I see the daily updated log?

### ISSUE THREAD

**Issue by k2y1982** [bugprogrammer/HackinPlugins#2]
There seems to be something wrong with yesterday's（4-13）.

OpenCore-0.6.9-RELEASE。

**Comment by k2y1982** [comment]
同样的设置，今天（4-14）的OpenCore-0.6.9-RELEASE就没有报错了，能正常进引导界面。

**Comment by bugprogrammer** [comment]
我只是按照源码编译的，某些日期的有bug是源码本身的问题。

I just compiled it with the source code. The bugs on certain dates are the source code itself.
